# https://docs.github.com/en/actions/examples/using-scripts-to-test-your-code-on-a-runner


name: FastAPP YAML

on: [push, pull_request]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: pull repo
        uses: actions/checkout@v3
      - name: install python v3.11
        uses: actions/checkout@v3
        with:
          python-version: '3.11' 
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: intall dependencies
        run: pip install -r req
