# https://docs.github.com/en/actions/examples/using-scripts-to-test-your-code-on-a-runner

name: FastAPP YAML

on: [push, pull_request]

jobs:
  job-1:
    environment:  
      name: prod
    env:
        DATABASE_HOSTNAME: ${{secrets.DATABASE_HOSTNAME}}
        DATABASE_PORT:  ${{secrets.DATABASE_PORT}}
        DATABASE_PASSWORD:  ${{secrets.DATABASE_PASSWORD}}
        DATABASE_NAME:  ${{secrets.DATABASE_NAME}}
        DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
        DATABASE_URL:  ${{secrets.DATABASE_URL}}
        DATABASE_URL_ALEMBIC:  ${{secrets.DATABASE_URL_ALEMBIC}}
        SECRETE_KEY:  ${{secrets.SECRETE_KEY}}
        ALGORITHM: ${{secrets.ALGORITHM}}
        ACCESS_TOKEN_EXPIRE_MINUTES:  ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
# https://docs.github.com/en/actions/security-guides/encrypted-secrets
    
    runs-on: ubuntu-latest

    steps:
      - name: pull repo
        uses: actions/checkout@v3

      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: update pip
        run: python -m pip install --upgrade pip

      - name: intall dependencies
        run: pip install -r req
        
      - name: run pytest
        run: pytest